name: Price logger

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run price logger
        run: python sheets.py
        env:
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          MASSIVE_API_KEY: ${{ secrets.MASSIVE_API_KEY }}
          GOOGLE_SHEETS_KEY: ${{ secrets.GOOGLE_SHEETS_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_RECIPIENT: ${{ secrets.GMAIL_RECIPIENT }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
